### ISSUE TITLE
package code.google.com/p/gcfg: unrecognized import path

### ISSUE THREAD

**Issue by worddevfr** [SeHarrys/PMS#1]
> go get github.com/SeHarrys/PMS
package code.google.com/p/gcfg: unrecognized import path "code.google.com/p/gcfg" (parse https://code.google.com/p/gcfg?go-get=1: no go-import meta tags ())

> go build
pms.go:11:2: cannot find package "code.google.com/p/gcfg" in any of:
        C:\Go\src\code.google.com\p\gcfg (from $GOROOT)
        C:\GoPath\src\code.google.com\p\gcfg (from $GOPATH)

**Comment by SeHarrys** [comment]
Google code it's not longer working, the packages is available in : gopkg.in/gcfg.v1

In a few days i upload a new version but this program will only work on Linux
